[package]
name = "protodec-rs"
version = "0.1.0"
authors = ["MD-Levitan <ovsyanka@protonmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
colored = "2"
clap = "2.33.1"
log4rs = "1.0.0"
log ="0.4.14"